name: publish release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        # maximize compatibility with minecraft images
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test

    - name: Release
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jreleaserFullRelease
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JRELEASER_SCOOP_GITHUB_TOKEN: ${{ secrets.PUSH_ACCESS_GITHUB_TOKEN }}
        JRELEASER_HOMEBREW_GITHUB_TOKEN: ${{ secrets.PUSH_ACCESS_GITHUB_TOKEN }}

    - name: Archive jreleaser trace log
      uses: actions/upload-artifact@v3
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: jrelease-trace-log
        path: build/jreleaser/trace.log
