name: start patch release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:
          # maximize compatibility with minecraft images
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Git config
        uses: fregante/setup-git-user@v1

      - name: Build with Gradle
        run: ./gradlew release -PpushReleaseTag=true
